### ISSUE TITLE
OnErrorNotImplementedException, occued when emulator call to my htc u play

### ISSUE THREAD

**Issue by BrokenPen** [seamlik/viska-android#4]
I add this to fix

https://github.com/BrokenPen/viska-android/commit/1e671075515bfea074bac74d3c519f0e6942728c

W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:129)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.onNext(FlowableFilter.java:119)
W/System.err:     at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
W/System.err:     at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
W/System.err:     at io.reactivex.processors.SerializedProcessor.onNext(SerializedProcessor.java:102)
W/System.err:     at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin.consumeIq(WebRtcPlugin.java:196)
W/System.err:     at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin.bridge$lambda$0$WebRtcPlugin(WebRtcPlugin.java)
W/System.err:     at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin$$Lambda$8.accept(Unknown Source)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.onNext(FlowableFilter.java:119)
W/System.err:     at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
W/System.err:     at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
W/System.err:     at chat.viska.xmpp.Session$PluginContext$$Lambda$3.accept(Unknown Source)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
W/System.err:     at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
W/System.err:     at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
W/System.err:     at io.reactivex.processors.SerializedProcessor.onNext(SerializedProcessor.java:102)
W/System.err:     at chat.viska.commons.pipelines.Pipeline.processObject(Pipeline.java:148)
W/System.err:     at chat.viska.commons.pipelines.Pipeline.lambda$start$0$Pipeline(Pipeline.java:261)
W/System.err:     at chat.viska.commons.pipelines.Pipeline$$Lambda$0.call(Unknown Source)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:685)
W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:672)
W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
W/System.err:     at chat.viska.android.XmppService.lambda$constructSession$4$XmppService(XmppService.java:177)
W/System.err:     at chat.viska.android.XmppService$$Lambda$3.accept(Unknown Source)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
W/System.err: 	... 32 more
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
                  Process: chat.viska, PID: 20919
                  io.reactivex.exceptions.OnErrorNotImplementedException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                      at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
                      at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:129)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.onNext(FlowableFilter.java:119)
                      at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
                      at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
                      at io.reactivex.processors.SerializedProcessor.onNext(SerializedProcessor.java:102)
                      at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin.consumeIq(WebRtcPlugin.java:196)
                      at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin.bridge$lambda$0$WebRtcPlugin(WebRtcPlugin.java)
                      at chat.viska.xmpp.plugins.webrtc.WebRtcPlugin$$Lambda$8.accept(Unknown Source)
                      at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.tryOnNext(FlowableFilter.java:141)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterConditionalSubscriber.onNext(FlowableFilter.java:119)
                      at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
                      at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
                      at chat.viska.xmpp.Session$PluginContext$$Lambda$3.accept(Unknown Source)
                      at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                      at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                      at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.onNext(FlowableMap.java:112)
                      at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
                      at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
                      at io.reactivex.processors.SerializedProcessor.onNext(SerializedProcessor.java:102)
                      at chat.viska.commons.pipelines.Pipeline.processObject(Pipeline.java:148)
                      at chat.viska.commons.pipelines.Pipeline.lambda$start$0$Pipeline(Pipeline.java:261)
                      at chat.viska.commons.pipelines.Pipeline$$Lambda$0.call(Unknown Source)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                      at android.app.ContextImpl.startActivity(ContextImpl.java:685)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:672)
                      at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
                  	at chat.viska.android.XmppService.lambda$constructSession$4
I/[MALI][Gralloc]: [-]r_hnd(0x7f9600a2a0), client(43), share_fd(156)
I/[MALI][Gralloc]: [-]r_hnd(0x7f9600ad40), client(43), share_fd(162)
I/[MALI][Gralloc]: [-]r_hnd(0x7f96008f40), client(43), share_fd(108)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f95ffc6a0
D/mali_winsys: [MALI] win=0xaed20210, native_buffer=0x95fbf110, fd=-1
I/[MALI][Gralloc]: [-]r_hnd(0x7f95ffc6a0), client(43), share_fd(55)
D/WindowClient: Remove from mViews: com.android.internal.policy.PhoneWindow$DecorView{58a1cab V.E...... R......D 0,0-1080,1920}, this = android.view.WindowManagerGlobal@9c00b50
D/Process: killProcess, pid=20919
D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 
Disconnected from the target VM, address: 'localhost:8617', transport:

**Comment by seamlik** [comment]
Fixed by 7f8eb9dee82879a3ca846ffd3bdb7e9887bb4f9d
